version: "3.8"
services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src

  backend:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/src:/app/src

  proxy:
    volumes:
      - ./proxy/nginx-dev.conf:/etc/nginx/conf.d/default.conf
