version: "3.8"
services:
  frontend:
    build:
      context: frontend
    depends_on:
      - backend
    networks:
      - local

  backend:    
    build:
      context: backend
    networks:
      - local

  proxy:
    image: nginx:1.13-alpine
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - frontend
      - backend
    networks:
      - local

networks:
  local: {}
